version: '3.8'

services:
  db:
    image: postgres
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust" 
    restart: always
    expose:
      - "5432"
    ports:
    - "5432:5432"
    secrets:
      - env
    volumes:
      - db:/var/lib/posgresql/data

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db

volumes:
  db:


secrets:
  env:
    file: ./.env
